### ISSUE TITLE
Pickle Error Captured

### ISSUE THREAD

**Issue by support-thinkingengine** [ThinkingEngine-net/PickleTestSuite#99] opened 2022-09-01 16:09 UTC
Build: 
Pickle Application : 1.17.0.4
Pickle Core : 1.17.0.4
Pickle Automation : 1.17.0.4
Pickle Console : 1.0.0.0
Build Architecture: Amd64
When: 01/09/2022 16:09 UTC
.Net #: Above version 4.7.1 [528372] - 4.0.30319.42000
OS #: Microsoft Windows NT 6.2.9200.0
OS Architecture: 64 bit
Memory Available: 727MB
CPU Used: 0%

 --------------- Error Stack Trace --------------
   in pickle.core.testCycle.ExportResultsAsSheets(String FileName)
   in pickle.frmResults.ExportAsSheets(String fileName)
   in pickle.frmPickle.mnuSaveAs_Click(Object sender, EventArgs e)
   in System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   in System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   in System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   in System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   in System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   in System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   in System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.ToolStrip.WndProc(Message& m)
   in System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
 ---------------End Stack Trace --------------

 --------------- Error Handler Stack Trace --------------
[0] GetExecutingStackTrace at offset 73 in file:line:column <filename unknown>:0:0

[1] setError at offset 1398 in file:line:column <filename unknown>:0:0

[2] ReportError at offset 50 in file:line:column <filename unknown>:0:0

[3] Application_ThreadException at offset 28 in file:line:column <filename unknown>:0:0

[4] OnThreadException at offset 168 in file:line:column <filename unknown>:0:0

[5] WndProcException at offset 28 in file:line:column <filename unknown>:0:0

[6] Callback at offset 194 in file:line:column <filename unknown>:0:0

[7] DispatchMessageW at offset 0 in file:line:column <filename unknown>:0:0

[8] DispatchMessageW at offset 0 in file:line:column <filename unknown>:0:0

[9] System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop at offset 833 in file:line:column <filename unknown>:0:0

[10] RunMessageLoopInner at offset 455 in file:line:column <filename unknown>:0:0

[11] RunMessageLoop at offset 82 in file:line:column <filename unknown>:0:0

[12] Main at offset 237 in file:line:column <filename unknown>:0:0

 ---------------End Stack Trace --------------

 --------------- Location --------------

 Target: Void ExportResultsAsSheets(System.String)
 Where: pickle.core
 ---------------End Location --------------

 --------------- Error --------------
System.IO.FileLoadException: Non è stato possibile caricare il file o l"assembly "Syncfusion.XlsIO.Base, Version=20.1450.0.55, Culture=neutral, PublicKeyToken=3d67ed1f87d44c89" o una delle relative dipendenze. La definizione di manifesto dell"assembly specificato non corrisponde al riferimento all"assembly. (Eccezione da HRESULT: 0x80131040)
Nome file: "Syncfusion.XlsIO.Base, Version=20.1450.0.55, Culture=neutral, PublicKeyToken=3d67ed1f87d44c89"
   in pickle.core.testCycle.ExportResultsAsSheets(String FileName)
   in pickle.frmResults.ExportAsSheets(String fileName)
   in pickle.frmPickle.mnuSaveAs_Click(Object sender, EventArgs e)
   in System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   in System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   in System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   in System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   in System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   in System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   in System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.ToolStrip.WndProc(Message& m)
   in System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

AVV: la registrazione dell"associazione di assembly è disattivata.
Per abilitare la registrazione degli errori di associazione di assembly, impostare il valore del Registro di sistema [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) su 1.
Nota: alcune penalità di prestazione sono associate alla registrazione degli errori di associazione di assembly.
Per disattivare la funzionalità, rimuovere il valore del Registro di sistema [HKLM\Software\Microsoft\Fusion!EnableLog].

 ---------------End Error --------------

 --------------- Active Source --------------
## Applies to: CONIK
@User

Feature: Turn the appliance on and off
           The appliance can be switched on and off by turning the general switch
           
    Background: Ensure that the general switch is turned off and the appliance is completely mounted

    Scenario: Appliance ignition
        Given   The appliance is switched off
        When    The user turns the general switch in position "1"
        Then    The appliance switches on
            And    The screen shows the software version, the release date and "CIMBALI" logo for a few seconds # Is the color of the logo to add?
            And    After about "15" seconds the main screen is displayed
        
    Scenario: Automatic start of the grinder
        Given   The main screen appeared on the screen
        When    The level of ground coffee in the doser is below the default minimum threshold # the threshold is to be defined
        Then    The grinder starts running automatically 
    
    Scenario: Automatic cut-off
        Given   The doser is automatically filling up 
        When    The doser has sufficient quantity of ground coffee # the sufficient quantity of ground coffee is to be defined 
        Then    The grinder stops running automatically 
        
    Scenario: Appliance shutdown
        Given   The appliance is on  
        When    The user turns the general switch in position "0"
        Then    The appliance switches off
 --------------- Active Source --------------

**Comment by ThinkingEngine-net** [comment] 2022-10-15 06:20
Duplicate of #100

**Closed by ThinkingEngine-net** 2022-10-15 06:20 UTC
Labels: bug, duplicate
