### ISSUE TITLE
Pickle Error Captured

### ISSUE THREAD

**Issue by support-thinkingengine** [ThinkingEngine-net/PickleTestSuite#70] opened 2021-09-02 09:30 UTC
Build: 
Pickle Application : Unknown
Pickle Core : Unknown
Pickle Automation : Unknown
Pickle Console : Unknown
Build Architecture: Amd64
When: 02-09-2021 09:29 UTC
.Net #: Above version 4.7.1 [528372] - 4.0.30319.42000
OS #: Microsoft Windows NT 6.2.9200.0
OS Architecture: 64 bit
Memory Available: 1652MB
CPU Used: 0%

 --------------- Error Stack Trace --------------
   at System.Drawing.Graphics.GetHdc()
   at Syncfusion.Windows.Forms.ControlDrawing.MeasureDisplayStringSize(Graphics graphics, String text, Font font, Boolean mirrored, Int32 width)
   at Syncfusion.Windows.Forms.Tools.TabRendererBase.MeasureText(Graphics g, String text, Font font)
   at Syncfusion.Windows.Forms.Tools.TabRendererBase.GetItemPreferredSize(Graphics g)
   at Syncfusion.Windows.Forms.Tools.TabPanelRenderer.GetLargestHeight(Graphics g)
   at Syncfusion.Windows.Forms.Tools.MultilineTabPanelRenderer.ComputeTabPositions(Graphics g)
   at Syncfusion.Windows.Forms.Tools.TabPanelRenderer.Layout(Graphics g, Boolean fromPaint)
   at Syncfusion.Windows.Forms.Tools.TabControlAdv.Layout(Graphics g, Boolean fromPaint)
   at Syncfusion.Windows.Forms.Tools.TabControlAdv.OnLayout(LayoutEventArgs levent)
   at System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
   at System.Windows.Forms.Control.OnResize(EventArgs e)
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at Syncfusion.Windows.Forms.Tools.TabControlAdv.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at Syncfusion.Windows.Forms.Tools.TabControlAdv.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
 ---------------End Stack Trace --------------

 --------------- Error Handler Stack Trace --------------
[0] GetExecutingStackTrace at offset 73 in file:line:column <filename unknown>:0:0

[1] setError at offset 1398 in file:line:column <filename unknown>:0:0

[2] ReportError at offset 50 in file:line:column <filename unknown>:0:0

[3] Application_ThreadException at offset 28 in file:line:column <filename unknown>:0:0

[4] OnThreadException at offset 168 in file:line:column <filename unknown>:0:0

[5] WndProcException at offset 28 in file:line:column <filename unknown>:0:0

[6] Callback at offset 194 in file:line:column <filename unknown>:0:0

[7] CallWindowProc at offset 0 in file:line:column <filename unknown>:0:0

[8] CallWindowProc at offset 0 in file:line:column <filename unknown>:0:0

[9] DefWndProc at offset 157 in file:line:column <filename unknown>:0:0

[10] WmWindowPosChanged at offset 48 in file:line:column <filename unknown>:0:0

[11] WndProc at offset 753 in file:line:column <filename unknown>:0:0

[12] WndProc at offset 324 in file:line:column <filename unknown>:0:0

[13] Callback at offset 194 in file:line:column <filename unknown>:0:0

[14] SetWindowPos at offset 0 in file:line:column <filename unknown>:0:0

[15] SetWindowPos at offset 0 in file:line:column <filename unknown>:0:0

[16] SetBoundsCore at offset 503 in file:line:column <filename unknown>:0:0

[17] System.Windows.Forms.Layout.IArrangedElement.SetBounds at offset 146 in file:line:column <filename unknown>:0:0

[18] xLayoutDockedControl at offset 68 in file:line:column <filename unknown>:0:0

[19] LayoutDockedControls at offset 1039 in file:line:column <filename unknown>:0:0

[20] xLayout at offset 357 in file:line:column <filename unknown>:0:0

[21] LayoutCore at offset 27 in file:line:column <filename unknown>:0:0

[22] Layout at offset 40 in file:line:column <filename unknown>:0:0

[23] OnLayout at offset 185 in file:line:column <filename unknown>:0:0

[24] OnLayout at offset 66 in file:line:column <filename unknown>:0:0

[25] PerformLayout at offset 256 in file:line:column <filename unknown>:0:0

[26] OnResize at offset 113 in file:line:column <filename unknown>:0:0

[27] OnResize at offset 18 in file:line:column <filename unknown>:0:0

[28] OnSizeChanged at offset 52 in file:line:column <filename unknown>:0:0

[29] UpdateBounds at offset 184 in file:line:column <filename unknown>:0:0

[30] UpdateBounds at offset 318 in file:line:column <filename unknown>:0:0

[31] WmWindowPosChanged at offset 57 in file:line:column <filename unknown>:0:0

[32] WndProc at offset 753 in file:line:column <filename unknown>:0:0

[33] WndProc at offset 486 in file:line:column <filename unknown>:0:0

[34] Callback at offset 194 in file:line:column <filename unknown>:0:0

[35] DefWndProc at offset 277 in file:line:column <filename unknown>:0:0

[36] WndProc at offset 116 in file:line:column <filename unknown>:0:0

[37] Callback at offset 194 in file:line:column <filename unknown>:0:0

[38] SetWindowRgn at offset 0 in file:line:column <filename unknown>:0:0

[39] SetWindowRgn at offset 0 in file:line:column <filename unknown>:0:0

[40] UpdateRegion at offset 278 in file:line:column <filename unknown>:0:0

[41] PreFilterMessage at offset 53 in file:line:column <filename unknown>:0:0

[42] WndProc at offset 45 in file:line:column <filename unknown>:0:0

[43] Callback at offset 194 in file:line:column <filename unknown>:0:0

[44] DefMDIChildProc at offset 0 in file:line:column <filename unknown>:0:0

[45] DefMDIChildProc at offset 0 in file:line:column <filename unknown>:0:0

[46] DefWndProc at offset 244 in file:line:column <filename unknown>:0:0

[47] WmWindowPosChanged at offset 48 in file:line:column <filename unknown>:0:0

[48] WndProc at offset 753 in file:line:column <filename unknown>:0:0

[49] WndProc at offset 486 in file:line:column <filename unknown>:0:0

[50] Callback at offset 194 in file:line:column <filename unknown>:0:0

[51] DefWndProc at offset 277 in file:line:column <filename unknown>:0:0

[52] WndProc at offset 116 in file:line:column <filename unknown>:0:0

[53] Callback at offset 194 in file:line:column <filename unknown>:0:0

[54] SetWindowPos at offset 0 in file:line:column <filename unknown>:0:0

[55] SetWindowPos at offset 0 in file:line:column <filename unknown>:0:0

[56] SetBoundsCore at offset 503 in file:line:column <filename unknown>:0:0

[57] SetBoundsCore at offset 314 in file:line:column <filename unknown>:0:0

[58] SetBounds at offset 128 in file:line:column <filename unknown>:0:0

[59] set_Size at offset 44 in file:line:column <filename unknown>:0:0

[60] SetClientSizeCore at offset 66 in file:line:column <filename unknown>:0:0

[61] SetClientSizeCore at offset 69 in file:line:column <filename unknown>:0:0

[62] set_ClientSize at offset 32 in file:line:column <filename unknown>:0:0

[63] UpdateFormStyles at offset 245 in file:line:column <filename unknown>:0:0

[64] set_FormBorderStyle at offset 331 in file:line:column <filename unknown>:0:0

[65] ChangeFormStyles at offset 415 in file:line:column <filename unknown>:0:0

[66] RemoveMdiChild at offset 66 in file:line:column <filename unknown>:0:0

[67] DetachMdiChildren at offset 156 in file:line:column <filename unknown>:0:0

[68] Dispose at offset 146 in file:line:column <filename unknown>:0:0

[69] WmClose at offset 1077 in file:line:column <filename unknown>:0:0

[70] Callback at offset 194 in file:line:column <filename unknown>:0:0

[71] SendMessage at offset 0 in file:line:column <filename unknown>:0:0

[72] SendMessage at offset 0 in file:line:column <filename unknown>:0:0

[73] SendMessage at offset 70 in file:line:column <filename unknown>:0:0

[74] Close at offset 74 in file:line:column <filename unknown>:0:0

[75] RemoveTabHost at offset 539 in file:line:column <filename unknown>:0:0

[76] DetachFromMdiContainer at offset 1368 in file:line:column <filename unknown>:0:0

[77] Invoke at offset 0 in file:line:column <filename unknown>:0:0

[78] OnFormClosed at offset 175 in file:line:column <filename unknown>:0:0

[79] WmClose at offset 1059 in file:line:column <filename unknown>:0:0

[80] Callback at offset 194 in file:line:column <filename unknown>:0:0

[81] DefWndProc at offset 277 in file:line:column <filename unknown>:0:0

[82] WndProc at offset 23 in file:line:column <filename unknown>:0:0

[83] Callback at offset 194 in file:line:column <filename unknown>:0:0

[84] DefFrameProc at offset 0 in file:line:column <filename unknown>:0:0

[85] DefFrameProc at offset 0 in file:line:column <filename unknown>:0:0

[86] DefWndProc at offset 211 in file:line:column <filename unknown>:0:0

[87] WndProc at offset 2103 in file:line:column <filename unknown>:0:0

[88] WmSysCommand at offset 321 in file:line:column <filename unknown>:0:0

[89] Callback at offset 194 in file:line:column <filename unknown>:0:0

[90] DefWndProc at offset 277 in file:line:column <filename unknown>:0:0

[91] WndProc at offset 23 in file:line:column <filename unknown>:0:0

[92] Callback at offset 194 in file:line:column <filename unknown>:0:0

[93] PeekMessage at offset 0 in file:line:column <filename unknown>:0:0

[94] PeekMessage at offset 0 in file:line:column <filename unknown>:0:0

[95] System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop at offset 576 in file:line:column <filename unknown>:0:0

[96] RunMessageLoopInner at offset 455 in file:line:column <filename unknown>:0:0

[97] RunMessageLoop at offset 82 in file:line:column <filename unknown>:0:0

[98] Main at offset 236 in file:line:column <filename unknown>:0:0

 ---------------End Stack Trace --------------

 --------------- Location --------------

 Target: IntPtr GetHdc()
 Where: System.Drawing
 ---------------End Location --------------

 --------------- Error --------------
System.InvalidOperationException: Object is currently in use elsewhere.
   at System.Drawing.Graphics.GetHdc()
   at Syncfusion.Windows.Forms.ControlDrawing.MeasureDisplayStringSize(Graphics graphics, String text, Font font, Boolean mirrored, Int32 width)
   at Syncfusion.Windows.Forms.Tools.TabRendererBase.MeasureText(Graphics g, String text, Font font)
   at Syncfusion.Windows.Forms.Tools.TabRendererBase.GetItemPreferredSize(Graphics g)
   at Syncfusion.Windows.Forms.Tools.TabPanelRenderer.GetLargestHeight(Graphics g)
   at Syncfusion.Windows.Forms.Tools.MultilineTabPanelRenderer.ComputeTabPositions(Graphics g)
   at Syncfusion.Windows.Forms.Tools.TabPanelRenderer.Layout(Graphics g, Boolean fromPaint)
   at Syncfusion.Windows.Forms.Tools.TabControlAdv.Layout(Graphics g, Boolean fromPaint)
   at Syncfusion.Windows.Forms.Tools.TabControlAdv.OnLayout(LayoutEventArgs levent)
   at System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
   at System.Windows.Forms.Control.OnResize(EventArgs e)
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at Syncfusion.Windows.Forms.Tools.TabControlAdv.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at Syncfusion.Windows.Forms.Tools.TabControlAdv.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
 ---------------End Error --------------

**Comment by ThinkingEngine-net** [comment] 2021-10-02 09:29
Duplicate of #71

**Closed by ThinkingEngine-net** 2021-10-02 09:29 UTC
Labels: bug, duplicate
