### ISSUE TITLE
Pickle Error Captured

### ISSUE THREAD

**Issue by support-thinkingengine** [ThinkingEngine-net/PickleTestSuite#95] opened 2022-06-20 09:23 UTC
Build: 
Pickle Application : 1.17.0.4
Pickle Core : 1.17.0.4
Pickle Automation : 1.17.0.4
Pickle Console : 1.0.0.0
Build Architecture: X86
When: 20/06/2022 09:23 UTC
.Net #: Above version 4.7.1 [528372] - 4.0.30319.42000
OS #: Microsoft Windows NT 6.2.9200.0
OS Architecture: 64 bit
Memory Available: 8125MB
CPU Used: 0%

 --------------- Error Stack Trace --------------
   in pickle.core.testCycle.ExportResultsAsSheets(String FileName)
   in pickle.frmResults.ExportAsSheets(String fileName)
   in pickle.frmPickle.mnuSaveAs_Click(Object sender, EventArgs e)
   in pickle.frmPickle.mnuSave_Click(Object sender, EventArgs e)
   in System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   in System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   in System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   in System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   in System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   in System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   in System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   in System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   in System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   in System.Windows.Forms.ToolStrip.WndProc(Message& m)
   in System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
 ---------------End Stack Trace --------------

 --------------- Error Handler Stack Trace --------------
[0] GetExecutingStackTrace at offset 50 in file:line:column <filename unknown>:0:0

[1] setError at offset 1149 in file:line:column <filename unknown>:0:0

[2] ReportError at offset 38 in file:line:column <filename unknown>:0:0

[3] Application_ThreadException at offset 16 in file:line:column <filename unknown>:0:0

[4] OnThreadException at offset 143 in file:line:column <filename unknown>:0:0

[5] WndProcException at offset 25 in file:line:column <filename unknown>:0:0

[6] OnThreadException at offset 16 in file:line:column <filename unknown>:0:0

[7] Callback at offset 175 in file:line:column <filename unknown>:0:0

[8] DispatchMessageW at offset 0 in file:line:column <filename unknown>:0:0

[9] System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop at offset 607 in file:line:column <filename unknown>:0:0

[10] RunMessageLoopInner at offset 373 in file:line:column <filename unknown>:0:0

[11] RunMessageLoop at offset 79 in file:line:column <filename unknown>:0:0

[12] Run at offset 53 in file:line:column <filename unknown>:0:0

[13] Main at offset 231 in file:line:column <filename unknown>:0:0

 ---------------End Stack Trace --------------

 --------------- Location --------------

 Target: Void ExportResultsAsSheets(System.String)
 Where: pickle.core
 ---------------End Location --------------

 --------------- Error --------------
System.IO.FileLoadException: Non è stato possibile caricare il file o l"assembly "Syncfusion.XlsIO.Base, Version=20.1450.0.55, Culture=neutral, PublicKeyToken=3d67ed1f87d44c89" o una delle relative dipendenze. La definizione di manifesto dell"assembly specificato non corrisponde al riferimento all"assembly. (Eccezione da HRESULT: 0x80131040)
Nome file: "Syncfusion.XlsIO.Base, Version=20.1450.0.55, Culture=neutral, PublicKeyToken=3d67ed1f87d44c89"
   in pickle.core.testCycle.ExportResultsAsSheets(String FileName)
   in pickle.frmResults.ExportAsSheets(String fileName)
   in pickle.frmPickle.mnuSaveAs_Click(Object sender, EventArgs e)
   in pickle.frmPickle.mnuSave_Click(Object sender, EventArgs e)
   in System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   in System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   in System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   in System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   in System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   in System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   in System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   in System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   in System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   in System.Windows.Forms.ToolStrip.WndProc(Message& m)
   in System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

AVV: la registrazione dell"associazione di assembly è disattivata.
Per abilitare la registrazione degli errori di associazione di assembly, impostare il valore del Registro di sistema [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) su 1.
Nota: alcune penalità di prestazione sono associate alla registrazione degli errori di associazione di assembly.
Per disattivare la funzionalità, rimuovere il valore del Registro di sistema [HKLM\Software\Microsoft\Fusion!EnableLog].

 ---------------End Error --------------

 --------------- Active Source --------------
{"Name":"Single Script - 01_01_01_AccensioneSpegnimentoMacchina","Description":"","ID":"21792767-e329-4f58-a2f9-6b433f6819f0","Scripts":[{"projectRelativePath":"","type":0,"lastGoodCompileCheckSum":"","CompileStatus":4,"GherkinCompileStatus":4,"lastError":"","rule":0,"Condition":"","CMDParams":"","CMD":"","ID":"7844fc7f-2168-4bf2-b79c-b0b33b0e20bf","InheritVars":true,"parent":"","Name":"01_01_01_AccensioneSpegnimentoMacchina","isNew":true,"cmdRegExpSuccess":"","browser":0,"customBrowserName":"Chrome"}]}

## Applies to: M100 attiva Cimbali

Feature: Accensione e spegnimento macchina
            La macchina può essere accesa e spenta tramite la pressione del tasto di accensione posto sul fianco della macchina.
            All"avviamento, la fase iniziale è quella di macchina fredda, dove la caldaia e i boiler raggiungono la pressione e
            la temperatura impostata per il normale funzionamento.
                  
    Scenario: Accensione macchina
        Given       La macchina è spenta
        When        L"utente preme il tasto di accensione
        Then        La macchina si accende
            And     Il display servizi si accende
            And     I display dei gruppi si accendono
            And     Compare il logo Cimbali e la barra di caricamento su tutti i display
            And     Il logo Cimbali e la barra di caricamento è nella corretta disposizione
    
    Scenario: comparsa schermata di boot
        Given       La macchina è appena stata accesa
            And     Compare il logo Cimbali e la barra di caricamento su tutti i display
        When        La barra di caricamento è completa di colore verde
        Then        Compare la schermata di boot
            And     Compare la versione firmware sui display
            And     La versione firmware è nella corretta disposizione 
    
    Scenario: display servizi in modalità erogazione acqua
        Given       La macchina è appena stata accesa
            And     Compare la schermata di boot
        When        L"utente attende qualche istante
        Then        Compare il nome della macchina e la versione sul display dei gruppi
            And     Compare il testo del gruppo sui display dei gruppi
            And     Il nome della macchina e la versione è nella corretta disposizione
            And     Il testo del gruppo è nella corretta disposizione
            And     Il display servizi è nella modalità erogazione acqua
    
    Scenario: normale visualizzazione display dei gruppi
        Given       La macchine è appena stata accesa
            And     Compare il nome della macchina e la versione sul display dei gruppi
            And     Compare il testo del gruppo sui display dei gruppi
        When        L"utente attende qualche istante
        Then        I display dei gruppi sono attivi
            And     I display dei gruppi presentano i tasti erogazione caffè

    Scenario: accensione macchina con dip 3 OFF
        Given       La macchina è appena stata accesa
            And     Compare la schermata di boot
            And     Il DIP 3 è OFF
        Then        La macchina non richiede l"aggiornamento Recovery
            And     Il buzzer non emette suono per aggiornamento Recovery
            
    Scenario: Spegnimento macchina
        Given       La macchina è accesa
        When        L"utente preme l"interruttore generale
        Then        La macchina si spegne
            And     Tutti i display sono spenti
 --------------- Active Source --------------

**Comment by ThinkingEngine-net** [comment] 2022-10-15 06:24
duplicate of #100

**Closed by ThinkingEngine-net** 2022-10-15 06:24 UTC
Labels: bug, duplicate
