### ISSUE TITLE
Pickle Error Captured

### ISSUE THREAD

**Issue by support-thinkingengine** [ThinkingEngine-net/PickleTestSuite#98] opened 2022-08-31 07:25 UTC
Build: 
Pickle Application : 1.17.0.4
Pickle Core : 1.17.0.4
Pickle Automation : 1.17.0.4
Pickle Console : 1.0.0.0
Build Architecture: Amd64
When: 31/08/2022 07:24 UTC
.Net #: Above version 4.7.1 [528372] - 4.0.30319.42000
OS #: Microsoft Windows NT 6.2.9200.0
OS Architecture: 64 bit
Memory Available: 7283MB
CPU Used: 0%

 --------------- Error Stack Trace --------------
   at pickle.core.testCycle.ExportResultsAsSheets(String FileName)
   at pickle.frmResults.ExportAsSheets(String fileName)
   at pickle.frmPickle.mnuSaveAs_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
 ---------------End Stack Trace --------------

 --------------- Error Handler Stack Trace --------------
[0] GetExecutingStackTrace at offset 73 in file:line:column <filename unknown>:0:0

[1] setError at offset 1397 in file:line:column <filename unknown>:0:0

[2] ReportError at offset 50 in file:line:column <filename unknown>:0:0

[3] Application_ThreadException at offset 28 in file:line:column <filename unknown>:0:0

[4] OnThreadException at offset 168 in file:line:column <filename unknown>:0:0

[5] WndProcException at offset 28 in file:line:column <filename unknown>:0:0

[6] Callback at offset 194 in file:line:column <filename unknown>:0:0

[7] DispatchMessageW at offset 0 in file:line:column <filename unknown>:0:0

[8] DispatchMessageW at offset 0 in file:line:column <filename unknown>:0:0

[9] System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop at offset 833 in file:line:column <filename unknown>:0:0

[10] RunMessageLoopInner at offset 455 in file:line:column <filename unknown>:0:0

[11] RunMessageLoop at offset 82 in file:line:column <filename unknown>:0:0

[12] Main at offset 237 in file:line:column <filename unknown>:0:0

 ---------------End Stack Trace --------------

 --------------- Location --------------

 Target: Void ExportResultsAsSheets(System.String)
 Where: pickle.core
 ---------------End Location --------------

 --------------- Error --------------
System.IO.FileLoadException: Could not load file or assembly "Syncfusion.XlsIO.Base, Version=20.1450.0.55, Culture=neutral, PublicKeyToken=3d67ed1f87d44c89" or one of its dependencies. The located assembly"s manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: "Syncfusion.XlsIO.Base, Version=20.1450.0.55, Culture=neutral, PublicKeyToken=3d67ed1f87d44c89"
   at pickle.core.testCycle.ExportResultsAsSheets(String FileName)
   at pickle.frmResults.ExportAsSheets(String fileName)
   at pickle.frmPickle.mnuSaveAs_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

 ---------------End Error --------------

 --------------- Active Source --------------
{"Name":"Single Script - 01_01_01_Appliance on_off","Description":"","ID":"37d82949-b56a-4949-8329-ff1c55e23262","Scripts":[{"projectRelativePath":"","type":0,"lastGoodCompileCheckSum":"","CompileStatus":4,"GherkinCompileStatus":4,"lastError":"","rule":0,"Condition":"","CMDParams":"","CMD":"","ID":"320f04b9-7b7c-4b48-8364-77bd19fdb8b7","InheritVars":true,"parent":"","Name":"01_01_01_Appliance on_off","isNew":true,"cmdRegExpSuccess":"","browser":0,"customBrowserName":"Chrome"}]}

## Applies to: CONIK
@User

Feature: Switching on/off the appliance
           Appliance can be switched on and off by turning on and off the general switch
           
    Scenario: Switching on 
    Given       Appliance is switched off
    When        User turns the general switch in position "1"
    Then        Appliance switches on
        And     Screen shows the boot logo and a progress bar with white background color
        And     Progress bar fills up and its background color turns green 
        And     Progress bar and the boot logo disappears and the "CIMBALI" logo is displayed 
        And     background color changes three times: red, purple, white  
        And     Software version and the release date is displayed below the logo
        And     "CIMBALI" logo, the software version and the release date disappear
        And     Main screen is displayed
            
    Scenario: Icons on the main screen
    Given       Main screen is displayed
    Then        The following icons appear on the main screen: "reference value", "coffee granulometry",
        And     "coarse grinding symbol", "fine grinding symbol", "bluetooth on", 
        And     "USER MENU","dose counter", "SETTING MENU"
        
    Scenario: Grinder automatic start
    Given       Main screen is displayed
    When        Level of ground coffee in the doser is below the default threshold 
    Then        Grinder starts running  
    
    Scenario: Grinder utomatic cut-off 
    Given       Level of ground coffee in the doser is below the default threshold 
        And     Grinder is running  
    When        Level of ground coffee in the doser is above the default threshold 
    Then        Grinder stops running 
        
    Scenario: Switching off
    Given   Appliance is on  
    When    User turns the general switch in position "0"
    Then    Appliance switches off
 --------------- Active Source --------------

**Comment by ThinkingEngine-net** [comment] 2022-10-15 06:21
Duplicate of #100

**Closed by ThinkingEngine-net** 2022-10-15 06:21 UTC
Labels: bug, duplicate
