### ISSUE TITLE
Pickle Error Captured

### ISSUE THREAD

**Issue by support-thinkingengine** [ThinkingEngine-net/PickleTestSuite#124] opened 2024-05-14 14:39 UTC
Build: 
Pickle Application : Unknown
Pickle Core : Unknown
Pickle Automation : Unknown
Pickle Console : Unknown
Build Architecture: Amd64
When: 14/05/2024 14:39 UTC
.Net #: Above version 4.7.1 [533325] - 4.0.30319.42000
OS #: Microsoft Windows NT 6.2.9200.0
OS Architecture: 64 bit
Memory Available: 6647MB
CPU Used: 0%

 --------------- Error Stack Trace --------------
   at pickle.core.testCycle.ExportResultsAsSheets(String FileName)
   at pickle.frmResults.ExportAsSheets(String fileName)
   at pickle.frmPickle.mnuSaveAs_Click(Object sender, EventArgs e)
   at pickle.frmPickle.mnuSave_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.ProcessCmdKey(Message& m, Keys keyData)
   at System.Windows.Forms.ToolStripManager.ProcessShortcut(Message& m, Keys shortcut)
   at System.Windows.Forms.Form.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Form.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
 ---------------End Stack Trace --------------

 --------------- Error Handler Stack Trace --------------
[0] GetExecutingStackTrace at offset 73 in file:line:column <filename unknown>:0:0

[1] setError at offset 1398 in file:line:column <filename unknown>:0:0

[2] ReportError at offset 50 in file:line:column <filename unknown>:0:0

[3] Application_ThreadException at offset 28 in file:line:column <filename unknown>:0:0

[4] OnThreadException at offset 168 in file:line:column <filename unknown>:0:0

[5] PreTranslateMessage at offset 137 in file:line:column <filename unknown>:0:0

[6] System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop at offset 800 in file:line:column <filename unknown>:0:0

[7] RunMessageLoopInner at offset 455 in file:line:column <filename unknown>:0:0

[8] RunMessageLoop at offset 82 in file:line:column <filename unknown>:0:0

[9] Main at offset 237 in file:line:column <filename unknown>:0:0

 ---------------End Stack Trace --------------

 --------------- Location --------------

 Target: Void ExportResultsAsSheets(System.String)
 Where: pickle.core
 ---------------End Location --------------

 --------------- Error --------------
System.IO.FileLoadException: Could not load file or assembly "Syncfusion.XlsIO.Base, Version=20.1450.0.55, Culture=neutral, PublicKeyToken=3d67ed1f87d44c89" or one of its dependencies. The located assembly"s manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: "Syncfusion.XlsIO.Base, Version=20.1450.0.55, Culture=neutral, PublicKeyToken=3d67ed1f87d44c89"
   at pickle.core.testCycle.ExportResultsAsSheets(String FileName)
   at pickle.frmResults.ExportAsSheets(String fileName)
   at pickle.frmPickle.mnuSaveAs_Click(Object sender, EventArgs e)
   at pickle.frmPickle.mnuSave_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.ProcessCmdKey(Message& m, Keys keyData)
   at System.Windows.Forms.ToolStripManager.ProcessShortcut(Message& m, Keys shortcut)
   at System.Windows.Forms.Form.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Form.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

 ---------------End Error --------------

**Comment by ThinkingEngine-net** [comment] 2024-07-17 18:37
duplicate of #129

**Closed as completed by ThinkingEngine-net** 2024-07-17 18:37 UTC
Labels: bug
