### ISSUE TITLE
Pickle Error Captured

### ISSUE THREAD

**Issue by support-thinkingengine** [ThinkingEngine-net/PickleTestSuite#123] opened 2024-05-10 11:03 UTC
Build: 
Pickle Application : Unknown
Pickle Core : Unknown
Pickle Automation : Unknown
Pickle Console : Unknown
Build Architecture: Amd64
When: 10/05/2024 11:03 UTC
.Net #: Above version 4.7.1 [533325] - 4.0.30319.42000
OS #: Microsoft Windows NT 6.2.9200.0
OS Architecture: 64 bit
Memory Available: 1049MB
CPU Used: 0%

 --------------- Error Stack Trace --------------
   at pickle.core.testCycle.ExportResultsAsSheets(String FileName)
   at pickle.frmResults.ExportAsSheets(String fileName)
   at pickle.frmPickle.mnuSaveAs_Click(Object sender, EventArgs e)
   at pickle.frmPickle.mnuSave_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
 ---------------End Stack Trace --------------

 --------------- Error Handler Stack Trace --------------
[0] GetExecutingStackTrace at offset 73 in file:line:column <filename unknown>:0:0

[1] setError at offset 1398 in file:line:column <filename unknown>:0:0

[2] ReportError at offset 50 in file:line:column <filename unknown>:0:0

[3] Application_ThreadException at offset 28 in file:line:column <filename unknown>:0:0

[4] OnThreadException at offset 168 in file:line:column <filename unknown>:0:0

[5] WndProcException at offset 28 in file:line:column <filename unknown>:0:0

[6] Callback at offset 194 in file:line:column <filename unknown>:0:0

[7] DispatchMessageW at offset 0 in file:line:column <filename unknown>:0:0

[8] DispatchMessageW at offset 0 in file:line:column <filename unknown>:0:0

[9] System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop at offset 833 in file:line:column <filename unknown>:0:0

[10] RunMessageLoopInner at offset 455 in file:line:column <filename unknown>:0:0

[11] RunMessageLoop at offset 82 in file:line:column <filename unknown>:0:0

[12] Main at offset 237 in file:line:column <filename unknown>:0:0

 ---------------End Stack Trace --------------

 --------------- Location --------------

 Target: Void ExportResultsAsSheets(System.String)
 Where: pickle.core
 ---------------End Location --------------

 --------------- Error --------------
System.IO.FileLoadException: Could not load file or assembly "Syncfusion.XlsIO.Base, Version=20.1450.0.55, Culture=neutral, PublicKeyToken=3d67ed1f87d44c89" or one of its dependencies. The located assembly"s manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: "Syncfusion.XlsIO.Base, Version=20.1450.0.55, Culture=neutral, PublicKeyToken=3d67ed1f87d44c89"
   at pickle.core.testCycle.ExportResultsAsSheets(String FileName)
   at pickle.frmResults.ExportAsSheets(String fileName)
   at pickle.frmPickle.mnuSaveAs_Click(Object sender, EventArgs e)
   at pickle.frmPickle.mnuSave_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

 ---------------End Error --------------

**Comment by ThinkingEngine-net** [comment] 2024-07-17 18:37
duplicate of #129

**Closed as completed by ThinkingEngine-net** 2024-07-17 18:37 UTC
Labels: bug
