### ISSUE TITLE
Pickle Error Captured

### ISSUE THREAD

**Issue by support-thinkingengine** [ThinkingEngine-net/PickleTestSuite#97] opened 2022-06-21 09:44 UTC
Build: 
Pickle Application : 1.17.0.4
Pickle Core : 1.17.0.4
Pickle Automation : 1.17.0.4
Pickle Console : 1.0.0.0
Build Architecture: Amd64
When: 21-06-2022 09:44 AM UTC
.Net #: Above version 4.7.1 [528372] - 4.0.30319.42000
OS #: Microsoft Windows NT 6.2.9200.0
OS Architecture: 64 bit
Memory Available: 1255MB
CPU Used: 0%

 --------------- Error Stack Trace --------------
   at pickle.core.testCycle.ExportResultsAsSheets(String FileName)
   at pickle.frmResults.ExportAsSheets(String fileName)
   at pickle.frmPickle.mnuSaveAs_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
 ---------------End Stack Trace --------------

 --------------- Error Handler Stack Trace --------------
[0] GetExecutingStackTrace at offset 73 in file:line:column <filename unknown>:0:0

[1] setError at offset 1398 in file:line:column <filename unknown>:0:0

[2] ReportError at offset 50 in file:line:column <filename unknown>:0:0

[3] Application_ThreadException at offset 28 in file:line:column <filename unknown>:0:0

[4] OnThreadException at offset 168 in file:line:column <filename unknown>:0:0

[5] WndProcException at offset 28 in file:line:column <filename unknown>:0:0

[6] Callback at offset 194 in file:line:column <filename unknown>:0:0

[7] DispatchMessageW at offset 0 in file:line:column <filename unknown>:0:0

[8] DispatchMessageW at offset 0 in file:line:column <filename unknown>:0:0

[9] System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop at offset 833 in file:line:column <filename unknown>:0:0

[10] RunMessageLoopInner at offset 455 in file:line:column <filename unknown>:0:0

[11] RunMessageLoop at offset 82 in file:line:column <filename unknown>:0:0

[12] Main at offset 237 in file:line:column <filename unknown>:0:0

 ---------------End Stack Trace --------------

 --------------- Location --------------

 Target: Void ExportResultsAsSheets(System.String)
 Where: pickle.core
 ---------------End Location --------------

 --------------- Error --------------
System.IO.FileLoadException: Could not load file or assembly "Syncfusion.XlsIO.Base, Version=20.1450.0.55, Culture=neutral, PublicKeyToken=3d67ed1f87d44c89" or one of its dependencies. The located assembly"s manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: "Syncfusion.XlsIO.Base, Version=20.1450.0.55, Culture=neutral, PublicKeyToken=3d67ed1f87d44c89"
   at pickle.core.testCycle.ExportResultsAsSheets(String FileName)
   at pickle.frmResults.ExportAsSheets(String fileName)
   at pickle.frmPickle.mnuSaveAs_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

 ---------------End Error --------------

 --------------- Active Source --------------
{"Name":"Single Script - UAT_SPRINT_6211","Description":"","ID":"aa466455-fc2c-4ed9-a86e-09ff43a3826b","Scripts":[{"projectRelativePath":"","type":0,"lastGoodCompileCheckSum":"","CompileStatus":4,"GherkinCompileStatus":4,"lastError":"","rule":0,"Condition":"","CMDParams":"","CMD":"","ID":"f368cd23-e269-4aad-a488-c9c815c03547","InheritVars":true,"parent":"","Name":"UAT_SPRINT_6211","isNew":true,"cmdRegExpSuccess":"","browser":0,"customBrowserName":"Chrome"}]}

# Author: Vikash Kumar
## Applies to: C&G Consolidation

Feature: Update an Account record (apart from Administrators)

Scenario Outline:   Login to D365 app as crm
Given I am on the URL: "https://newcrmpreprod.crm4.dynamics.com.mcas.ms/main.aspx"
Then I fill in "<username>" into the "Email" input box 
And I fill in "<password>" into the "Password" input box 
And I am on the Homepage
Examples: 
| url                                      | username                       |password   |
| https://newcrmpreprod.crm4.dynamics.com.mcas.ms/main.aspx | crmtest@cityandguilds.com  |(6,u2y$E1fm |
 

 Scenario: Accessing account records(8130)
Given:I am on D365 page and EY account doesn"t have account management role
Then I press on accounts option
And I should see "EY" Account name
Then I press on account name
And I should see name is not editable
Then I should not see "New" button

Scenario: Account creation with account management role(8361)
Given:I am on D365 homepage as  user A
Then I  press on accounts option
And I should see account page 
Then I press on "New" option
And I should be on "New Account" page

Scenario: Account creation with account management role own brand managgement role(8362)
Given:I am on D365 homepage as  user A and User A have Account management role with their own brand engagement (BU)
Then I  press on accounts option
And I should see account page 
Then I press on "New" option
And I should be on "New Account" page

Scenario: Account creation with account management role Any brand managgement role(8363)
Given:I am on D365 homepage as  user A and User A have Account management role with their different brand engagement (BU)
Then I  press on accounts option
And I should see account page 
Then I press on "New" option
And I should be on "New Account" page

Scenario: Account creation with account management role active brand managgement role(8364)
Given:I am on D365 homepage as  user A and User A have Account management role with their active brand engagement (BU)
Then I  press on accounts option
And I should see account page 
Then I press on "New" option
And I should be on "New Account" page
 --------------- Active Source --------------

**Comment by ThinkingEngine-net** [comment] 2022-10-15 06:22
duplicate of #100

**Closed by ThinkingEngine-net** 2022-10-15 06:22 UTC
Labels: bug, duplicate
